version: "2"
services:
  zoo1:
    image: "zookeeper:3.8.1"
    container_name: zoo1
    hostname: zoo1
    ports:
      - "2181:2181"
  kafka1:
    image: "bitnami/kafka:3.4.0"
    container_name: kafka1
    hostname: kafka1
    depends_on:
      - zoo1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BORKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,EXTERNAL://${KAFKA_HOST}:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT

  kafka2:
    image: "bitnami/kafka:3.4.0"
    container_name: kafka2
    hostname: kafka2
    depends_on:
      - zoo1
    ports:
      - "9102:9102"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BORKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,EXTERNAL://${KAFKA_HOST}:9102
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT

  kafka3:
    image: "bitnami/kafka:3.4.0"
    container_name: kafka3
    hostname: kafka3
    depends_on:
      - zoo1
    ports:
      - "9112:9112"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BORKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:9092,EXTERNAL://${KAFKA_HOST}:9112
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
